name: pass_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  # flutter: 2.0.2 - stable channel

dependencies:
  flutter:
    sdk: flutter
  animator: ^1.0.0+5
  auto_route: ^0.6.9
  auto_size_text: ^2.1.0
  barcode: ^1.17.1
  cached_network_image: ^2.5.0
  carousel_slider: ^2.3.1
  clippy_flutter: ^1.1.1
  connectivity: ^2.0.2
  cupertino_icons: ^1.0.0
  dart_notification_center: ^1.0.0+1
  dartz: ^0.9.1
  device_info: ^1.0.0
  dio: ^3.0.10
  enum_to_string: ^1.0.14
  equatable: ^2.0.0
  fancy_bottom_navigation: ^0.3.2
  fdottedline: ^1.0.1
  flappy_search_bar: ^1.7.2
  flare_flutter: ^2.0.6
  flare_splash_screen: ^3.0.1
  flutter_bloc: ^6.1.0
  flutter_email_sender: ^4.0.0
  flutter_html: ^1.1.1
  flutter_icons: ^1.1.0
  flutter_slidable: ^0.5.7
  flutter_staggered_grid_view: ^0.3.3
  flutter_svg: ^0.19.3
  font_awesome_flutter: ^8.10.0
  freezed_annotation: ^0.12.0
  get_it: ^4.0.4
  google_fonts: ^1.1.1
  home_indicator: ^1.1.5
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+14
  image_pixels: ^1.0.2
  infinite_scroll_pagination: ^2.2.2
  injectable: ^1.0.4
  intl: ^0.16.1
  jiffy: ^3.0.1
  json_annotation: ^3.0.1
  jwt_decode: ^0.1.0
  package_info: ^0.4.0+6
  path_provider: ^1.6.24
  photo_view: ^0.10.3
  pull_to_refresh: 1.6.4
  shared_preferences: ^0.5.8
  simple_animations: ^1.3.4
  smooth_page_indicator: ^0.2.0
  store_redirect: ^1.0.2
  tab_indicator_styler: ^1.0.0
  url_launcher: ^5.4.11

flutter_icons:
  includes:
    - ant

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.6.10
  freezed: ^0.12.6
  injectable_generator: ^1.0.4
  json_serializable: ^3.4.0
  lint: ^1.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: DejaVuSans
  #     fonts:
  #       - asset: assets/fonts/DejaVuSans-ExtraLight.ttf
  #         weight: 200
  #         style: normal
  #       - asset: assets/fonts/DejaVuSans.ttf
  #         weight: 400
  #         style: normal
  #       - asset: assets/fonts/DejaVuSansCondensed-Oblique.ttf
  #         weight: 400
  #         style: italic
  #       - asset: assets/fonts/DejaVuSansCondensed-Bold.ttf
  #         weight: 700
  #         style: normal
  #       - asset: assets/fonts/DejaVuSans-Bold.ttf
  #         weight: 700
  #         style: normal
  #       - asset: assets/fonts/DejaVuSans-BoldOblique.ttf
  #         weight: 700
  #         style: italic
  #       - asset: assets/fonts/DejaVuSansCondensed-BoldOblique.ttf
  #         weight: 700
  #         style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

